# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

lang: en-US
title: Royce Yap
email: royceyap at gmail dot com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Royce Yap
  Documentation of thoughts, works and plans for the future
baseurl: "" # the subpath of your site, e.g. /blog
url: "yap-r.github.io"
twitter_username: 
github_username:  yap-r

logo: /assets/icons/basically-basic-logo-light.svg
search: true
search_full_content: true
search_provider: algolia
algolia:
  application_id: QB6HVGBSBA
  index_name: basically-basic
  search_only_api_key: 9d5014e5bbc77372547bce778dfa5663
  powered_by: # true (default), false

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
remote_theme: "mmistakes/jekyll-theme-basically-basic"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml
# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  # _recipes
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      read_time: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
